use_frameworks!

target 'VisilabsIOS_Example' do
  pod 'VisilabsIOS', :path => '../'
  pod 'Eureka'
  pod 'Colorful'
  pod 'Euromsg'

  target 'VisilabsIOS_Tests' do
    inherit! :search_paths

    
  end
end
