name: CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['generic/platform=iOS Simulator']

    steps:
    - uses: actions/checkout@v2
    - name: Build Swift Package
      run: |
        set -o pipefail
        xcodebuild -scheme VisilabsIOS -destination '${{ matrix.destination }}' -derivedDataPath SpmBuild/ -configuration Debug clean build | xcpretty -c
    - name: Install Dependencies
      working-directory: Example
      run:
        pod install --repo-update
    - name: Run Test
      working-directory: Example
      run: |
        set -o pipefail
        xcodebuild -workspace VisilabsExample.xcworkspace -scheme VisilabsExample -derivedDataPath Build/ -destination '${{ matrix.destination }}' -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean build | xcpretty -c
    - name: Pod Lint
      run: pod lib lint --allow-warnings